In [4]:
import pandas as pd 

df = pd.read_csv("/home/kkyu/amr_ws/DL/IoT_Project/environment.csv")
df

,Date,Temperature (°C),Humidity (%),CO2 (PPM),PM-10 (μg/m3)
0,2024-03-09 15:25:34,25.1,5.0,161,27.98
1,2024-03-09 15:25:36,25.1,5.0,164,26.02
2,2024-03-09 15:25:37,25.1,5.0,163,27.00
3,2024-03-09 15:25:38,25.1,5.0,163,33.84
4,2024-03-09 15:25:39,25.1,5.0,163,27.98
5,2024-03-09 15:25:40,25.0,5.0,164,25.04
6,2024-03-09 15:25:41,25.0,5.0,163,27.00
7,2024-03-09 15:25:42,25.0,5.0,163,28.95
8,2024-03-09 15:25:43,25.0,5.0,163,27.98
9,2024-03-09 15:25:44,25.0,5.0,162,25.04
10,2024-03-09 15:25:45,25.0,5.0,162,25.04
11,2024-03-09 15:25:46,25.0,5.0,163,26.02